services:
  localstack:
    image: localstack/localstack:4.12.0
    container_name: subspace_secrets_localstack_test
    ports:
      - "4568:4566"
    environment:
      - SERVICES=ssm,secretsmanager
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=0
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
