services:
  redis:
    image: redis:8
    container_name: subspace_kv_redis_test
    ports:
      - "16381:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 30
